### ISSUE TITLE
FileSync PluginException : `ActionUpdateThread.OLD_EDT` is deprecated

### ISSUE THREAD

**Issue by tdargent1** [imyuyu/FileSyncPlugin#3]
Hello, there is an error when using the FileSync plugin (1.15.0) on IntelliJ (2024.2.3) :

>com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.imyuyu.idea.plugins.filesync.actions.RemoteSynchronizeSelectedAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: FileSync]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by imyuyu** [comment]
hi
Thank you for your report. I will check it later.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imyuyu/FileSyncPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月16日(星期三) 下午4:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[imyuyu/FileSyncPlugin] FileSync PluginException : `ActionUpdateThread.OLD_EDT` is deprecated (Issue #3)





 
Hello, there is an error when using the FileSync plugin (1.15.0) on IntelliJ (2024.2.3) :
  
com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon. 'org.imyuyu.idea.plugins.filesync.actions.RemoteSynchronizeSelectedAction' must override getActionUpdateThread() and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: FileSync]
 at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
 at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
 at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
 at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
 at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by imyuyu** [comment]
fixed.  [v1.15.1](https://github.com/imyuyu/FileSyncPlugin/releases/tag/v1.15.1)

Thanks again
